// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBPcHuWa034QUf2p_3WRcPu59OFngvdM',
    appId: '1:1022437937361:web:28afdd184406e8b651b5f0',
    messagingSenderId: '1022437937361',
    projectId: 'a-one-library-4f390',
    authDomain: 'a-one-library-4f390.firebaseapp.com',
    storageBucket: 'a-one-library-4f390.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDdSyTnrk8Gi6MMdm18evOVNn3mOaAeU',
    appId: '1:1022437937361:android:ec314d6b5a79c36f51b5f0',
    messagingSenderId: '1022437937361',
    projectId: 'a-one-library-4f390',
    storageBucket: 'a-one-library-4f390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnlrqGeA_60mkgxGf-xwlxGc0FgaC5H8',
    appId: '1:1022437937361:ios:6ca784a753fa014d51b5f0',
    messagingSenderId: '1022437937361',
    projectId: 'a-one-library-4f390',
    storageBucket: 'a-one-library-4f390.appspot.com',
    androidClientId: '1022437937361-abqlljqaq6r1k73vomh98c15vb2tburl.apps.googleusercontent.com',
    iosClientId: '1022437937361-i5pa7apltjmh2mng08oucc1r1vrv4am2.apps.googleusercontent.com',
    iosBundleId: 'com.neon.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnlrqGeA_60mkgxGf-xwlxGc0FgaC5H8',
    appId: '1:1022437937361:ios:04fd62fbae1905e751b5f0',
    messagingSenderId: '1022437937361',
    projectId: 'a-one-library-4f390',
    storageBucket: 'a-one-library-4f390.appspot.com',
    androidClientId: '1022437937361-abqlljqaq6r1k73vomh98c15vb2tburl.apps.googleusercontent.com',
    iosClientId: '1022437937361-m8t807465821uflmvf7316okumliep16.apps.googleusercontent.com',
    iosBundleId: 'com.aonelibrary.learningProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQBPcHuWa034QUf2p_3WRcPu59OFngvdM',
    appId: '1:1022437937361:web:a05ff93f0c61ca1151b5f0',
    messagingSenderId: '1022437937361',
    projectId: 'a-one-library-4f390',
    authDomain: 'a-one-library-4f390.firebaseapp.com',
    storageBucket: 'a-one-library-4f390.appspot.com',
  );
}
